# https://github.com/golangci/golangci-lint/blob/master/.golangci.example.yml
# https://golangci-lint.run/usage/configuration/
run:
  timeout: 5m

  sort-results: true

  # List of build tags, all linters use it.
  # Default: []
  build-tags:
    - mytag

  modules-download-mode: readonly

output:
  show-stats: true
  sort-results: true

linters:
  fast: false
  enable-all: true
  disable:
    - wsl
    - exhaustruct
    # disable deprecated linters
    - maligned
    - structcheck
    - scopelint
    - exhaustivestruct
    - nosnakecase
    - varcheck
    - interfacer
    - golint
    - ifshort
    - deadcode


linters-settings:
  varnamelen:
    min-name-length: 2
  misspell:
    locale: US
  depguard:
    # Rules to apply.
    #
    # Variables:
    # - File Variables
    #   you can still use and exclamation mark ! in front of a variable to say not to use it.
    #   Example !$test will match any file that is not a go test file.
    #
    #   `$all` - matches all go files
    #   `$test` - matches all go test files
    #
    # - Package Variables
    #
    #  `$gostd` - matches all of go's standard library (Pulled from `GOROOT`)
    #
    # Default: Only allow $gostd in all files.
    rules:
      # Name of a rule.
      main:
        # Used to determine the package matching priority.
        # There are three different modes: `original`, `strict`, and `lax`.
        # Default: "original"
        list-mode: strict
        # List of allowed packages.
        allow:
          - $gostd

issues:
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - dupl
        - funlen
        - gochecknoglobals
        - goconst
        - gocyclo
        - gosec
